### ISSUE TITLE
Refactor onPartChannels and onKickChannels

### ISSUE THREAD

**Issue by elazar** [enebe-nb/phergie-irc-plugin-react-autorejoin#1]
It looks like the implementations for [`onPartChannels()`](https://github.com/enebe-nb/phergie-irc-plugin-react-autorejoin/blob/16c21f62b8ea1a2c87d93ce120413efb5409688f/src/Plugin.php#L87-L90) and [`onKickChannels()`](https://github.com/enebe-nb/phergie-irc-plugin-react-autorejoin/blob/16c21f62b8ea1a2c87d93ce120413efb5409688f/src/Plugin.php#L102-L105) are identical except for the source of the event's originating user's nick. I'd suggest having these methods call a separate method that houses the bulk of the logic and accepts the user's nick as a parameter to reduce code duplication.

**Comment by enebe-nb** [comment]
This should make it.

**Comment by elazar** [comment]
Yup, looks good. :+1:
